services:
  ui:
    build:
      context: ./share
      dockerfile: Dockerfile
    container_name: sharing-ui
    ports:
      - "8000:8000"
    depends_on:
      - proxy
    restart: unless-stopped
    environment:
      - PORT=8000
    networks:
      - default

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: sharing-proxy
    ports:
      - "8001:8001"
    volumes:
      - ../data/proxy/uploads:/app/uploads
    restart: unless-stopped
    environment:
      - PORT=8001
    networks:
      - default

networks:
  default:
    name: shared-network
    external: true